### PR TITLE
Second task

### PR DESCRIPTION
**Pull request by coda93**

### CODE REVIEW

**Comment by MykhailoMalysh** [comment]
@coda93 First of all sorry for such delay in review
I have no comment to your implementation it seems that all functionality implemented correctly.
I only have doubts connected with investigation questions, like:
- Demonstrated understanding of the impact of changing the temperature value (10%)
- Try to play with the temperature value, what was changed?

And one more thing that I am not sure about, it is probably because I am not starting the application to receive a response, but it would be perfect if you highlight where I can found its implementation:
- Use ChatHistory to provide context about previous messages for a AI model.

So for now I can rate your implementation as - 75%

**Comment by coda93** [comment]
> @coda93 First of all sorry for such delay in review I have no comment to your implementation it seems that all functionality implemented correctly. I only have doubts connected with investigation questions, like:
> 
> * Demonstrated understanding of the impact of changing the temperature value (10%)
> * Try to play with the temperature value, what was changed?
> 
> And one more thing that I am not sure about, it is probably because I am not starting the application to receive a response, but it would be perfect if you highlight where I can found its implementation:
> 
> * Use ChatHistory to provide context about previous messages for a AI model.
> 
> So for now I can rate your implementation as - 75%

Mykhailo,
   No worries, I suppose that you are busy with working on client project, same as me. First of all, thank you for the detailed review and checking each required part. 
   Temperature, top_p and some other params as well are set used the route _/settings_, take a look at _ChatParams_ object. Also, charHistory is managed using _ChatHistoryManager_. I'll send you a postman collection via mail used for testing the app. You should set environment variables: 
          - client-openai-key: {YOUR_KEY}
          - client-openai-endpoint: https://your.ai-api.com/
          - client-openai-deployment-name: gpt-xx-turbo
in order to run the app.
   If it would be fasted I could make a small demo on Monday when you are available. Take care and have a nice weekend.

**Comment by coda93** [comment]
Mykhailo,

    Here is the mentioned Postman collection.

Regards,
Danilo

From: Misha Malysh ***@***.***>
Date: Saturday, 14 December 2024 at 13:39
To: coda93/AI-training ***@***.***>
Cc: Danilo Sucur ***@***.***>, Mention ***@***.***>
Subject: Re: [coda93/AI-training] Second task (PR #2)

@coda93<https://github.com/coda93> First of all sorry for such delay in review
I have no comment to your implementation it seems that all functionality implemented correctly.
I only have doubts connected with investigation questions, like:

  *   Demonstrated understanding of the impact of changing the temperature value (10%)
  *   Try to play with the temperature value, what was changed?

And one more thing that I am not sure about, it is probably because I am not starting the application to receive a response, but it would be perfect if you highlight where I can found its implementation:

  *   Use ChatHistory to provide context about previous messages for a AI model.

So for now I can rate your implementation as - 75%

**Comment by MykhailoMalysh** [comment]
Dear Danilo, thanks a lot for clarifications after it I have no objections for maximum rate

**Pull request merged**
